on: [push]

jobs:
  translate:
    runs-on: ubuntu-latest
    name: Translate stuff
    steps:
      - uses: actions/checkout@v4
      - name: translate-action
        uses: tcapelle/gpt_translate@v0.8.3
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
            folder-to-translate: 'docs/'
            language: "es"
            output-folder: "docs-es/"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Translated Docs
          title: Automatic translation
          body: This PR was automatically created by the translate-action
          branch: translated-docs-auto
          base: main