on: [push]

jobs:
  translate:
    runs-on: ubuntu-latest
    name: Translate stuff
    steps:
      - uses: actions/checkout@v4
      - name: translate-action
        uses: tcapelle/simple-translate-action@v2
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
            folder-to-translate: 'docs/'
            language: "es"
            output-folder: "docs-es/"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5