on: 
  pull_request:
    types: [closed]
    paths:
      - '**.md'

jobs:
  translate:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Translate stuff
    steps:
      - uses: actions/checkout@v4
      - name: translate-action
        id: translate-action
        uses: tcapelle/gpt_translate@v0.9.0
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
            folder-to-translate: 'docs/'
            language: "es"
            output-folder: "docs-es/"
            filter-files: "pr"  # only consider files that were modified in the PR

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: Translated Docs
          title: Automatic translation
          body: |
            This PR was automatically created by the translate-action. 
            
            The following files where changed: 
              $${{ steps.translate-action.outputs.translated-files }}
              Please review the changes and merge if they are correct.
          branch: translate-${{ github.event.pull_request.head.sha }}
          base: main
          delete-branch: true
          labels: translated